{% set name = "hackrf" %}
{% set version = "2021.03.1" %}

package:
    name: {{ name|lower }}
    version: {{ version }}

source:
    url: https://github.com/greatscottgadgets/{{ name }}/releases/download/v{{ version }}/{{ name }}-{{ version }}.tar.xz
    sha256: a43e5080c11efdfe69ddebcc35a02b018e30e820de0e0ebdc7948cf7b0cd93a3

build:
    number: 0

requirements:
    build:
        - {{ compiler('c') }}
        - cmake
        - ninja
    host:
        - libusb >=1
        - fftw
        - pthreads-win32
    run:
        - pthreads-win32

about:
    home: https://greatscottgadgets.com/
    license: GPL
    license_file: COPYING
    summary: host software for HackRF

